services:
  shelfly:
    build:
      context: .
      dockerfile: Shelfly.Api/Dockerfile
    container_name: shelfly
    hostname: shelfly
    ports:
      - "5000:8080"
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      mongodb:
        condition: service_started
    networks:
      - application_network
      - keycloak_network

  shelfly-db-init:
    build:
      context: ./database/postgresql
      dockerfile: Dockerfile.init
    env_file:
      - ../../deploy/envfiles/postgres-common.env
      - ./deploy/envfiles/postgres.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network
    profiles:
      - db-init
    secrets:
      - postgres_password
      - shelfly_admin_password
      - shelfly_user_password

  shelfly-mongo-init:
    image: mongodb/mongodb-community-server:8.3.2-ubuntu2204-slim
    restart: no
    env_file:
      - ../../deploy/envfiles/mongodb-common.env
      - ./deploy/envfiles/mongodb.env
    environment:
      - APP_MONGO_DATABASE=${MONGODB_SHELFLY_DATABASE}
      - APP_MONGO_USER=${MONGODB_SHELFLY_CONFIG_USER}
      - APP_MONGO_SECRET_FILE=mongodb_shelfly_config_password
    volumes:
      - ../../database/mongodb/01-create-mongo-user.sh:/mongo-init.sh:ro
    depends_on:
      mongodb:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - /mongo-init.sh
    networks:
      - application_network
    profiles:
      - mongo-init
    secrets:
      - mongodb_root_password
      - mongodb_shelfly_config_password

  shelfly-kc-import:
    build:
      context: ./keycloak
      dockerfile: Dockerfile.import
    depends_on:
      keycloak:
        condition: service_started
    networks:
      - keycloak_network
    profiles:
      - kc-import

networks:
  application_network:
    external: true
  keycloak_network:
    external: true

secrets:
  postgres_password:
    file: ./deploy/secrets/postgres_password.txt
  shelfly_admin_password:
    file: ./deploy/secrets/shelfly_admin_password.txt
  shelfly_user_password:
    file: ./deploy/secrets/shelfly_user_password.txt
  mongodb_root_password:
    file: ./deploy/secrets/mongodb_root_password.txt
  mongodb_shelfly_config_password:
    file: ./deploy/secrets/mongodb_shelfly_config_password.txt
