//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelfly.App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shelfly.App.Resources.Localization.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bücher.
        /// </summary>
        internal static string AppShellBooksTitle {
            get {
                return ResourceManager.GetString("AppShellBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen hinzufügen.
        /// </summary>
        internal static string BookDetailPageAddBookmarkButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageAddBookmarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Lesezeichen zu diesem Buch hinzufügen.
        /// </summary>
        internal static string BookDetailPageAddNewBookmarkDescription {
            get {
                return ResourceManager.GetString("BookDetailPageAddNewBookmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string BookDetailPageAuthorLabel {
            get {
                return ResourceManager.GetString("BookDetailPageAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchautor.
        /// </summary>
        internal static string BookDetailPageBookAuthorDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookAuthorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeicheneintrag. Nach links wischen zum Löschen. Notizsymbol tippen, um Notizinhalt anzuzeigen. Bearbeitungssymbol tippen, um Lesezeichen zu ändern..
        /// </summary>
        internal static string BookDetailPageBookmarkEntryDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichenliste.
        /// </summary>
        internal static string BookDetailPageBookmarkListDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seite {0}.
        /// </summary>
        internal static string BookDetailPageBookmarkPageLabel {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0}.
        /// </summary>
        internal static string BookDetailPageBookmarkRangeLabel {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichenbereich.
        /// </summary>
        internal static string BookDetailPageBookmarksSectionDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarksSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen.
        /// </summary>
        internal static string BookDetailPageBookmarksTitle {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchverlag.
        /// </summary>
        internal static string BookDetailPageBookPublisherDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookPublisherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchtitel.
        /// </summary>
        internal static string BookDetailPageBookTitleDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch löschen.
        /// </summary>
        internal static string BookDetailPageDeleteBookButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageDeleteBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string BookDetailPageDeleteBookmarkCommand {
            get {
                return ResourceManager.GetString("BookDetailPageDeleteBookmarkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch konnte nicht gelöscht werden.
        /// </summary>
        internal static string BookDetailPageDeletionFailedMessage {
            get {
                return ResourceManager.GetString("BookDetailPageDeletionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen fehlgeschlagen.
        /// </summary>
        internal static string BookDetailPageDeletionFailedTitle {
            get {
                return ResourceManager.GetString("BookDetailPageDeletionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch bearbeiten.
        /// </summary>
        internal static string BookDetailPageEditBookButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchdetails bearbeiten.
        /// </summary>
        internal static string BookDetailPageEditBookDescription {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string BookDetailPageEditBookmarkButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookmarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen bearbeiten.
        /// </summary>
        internal static string BookDetailPageEditBookmarkDescription {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internationale Standard-Buchnummer.
        /// </summary>
        internal static string BookDetailPageISBNDescription {
            get {
                return ResourceManager.GetString("BookDetailPageISBNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string BookDetailPageISBNLabel {
            get {
                return ResourceManager.GetString("BookDetailPageISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz.
        /// </summary>
        internal static string BookDetailPageNoteAlertTitle {
            get {
                return ResourceManager.GetString("BookDetailPageNoteAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz anzeigen.
        /// </summary>
        internal static string BookDetailPageNoteIndicatorTooltip {
            get {
                return ResourceManager.GetString("BookDetailPageNoteIndicatorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erscheinungsdatum.
        /// </summary>
        internal static string BookDetailPagePublicationDateDescription {
            get {
                return ResourceManager.GetString("BookDetailPagePublicationDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erscheinungsdatum.
        /// </summary>
        internal static string BookDetailPagePublishDateLabel {
            get {
                return ResourceManager.GetString("BookDetailPagePublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlag.
        /// </summary>
        internal static string BookDetailPagePublisherLabel {
            get {
                return ResourceManager.GetString("BookDetailPagePublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch und alle Lesezeichen weich löschen.
        /// </summary>
        internal static string BookDetailPageSoftDeleteBookDescription {
            get {
                return ResourceManager.GetString("BookDetailPageSoftDeleteBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchdetails.
        /// </summary>
        internal static string BookDetailPageTitle {
            get {
                return ResourceManager.GetString("BookDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz anzeigen.
        /// </summary>
        internal static string BookDetailPageViewNoteDescription {
            get {
                return ResourceManager.GetString("BookDetailPageViewNoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch hinzufügen.
        /// </summary>
        internal static string BookEditPageAddTitle {
            get {
                return ResourceManager.GetString("BookEditPageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor darf nicht leer sein.
        /// </summary>
        internal static string BookEditPageAuthorEmptyError {
            get {
                return ResourceManager.GetString("BookEditPageAuthorEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string BookEditPageAuthorLabel {
            get {
                return ResourceManager.GetString("BookEditPageAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor überschreitet maximale Länge von 256 Zeichen.
        /// </summary>
        internal static string BookEditPageAuthorMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPageAuthorMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch nicht gefunden.
        /// </summary>
        internal static string BookEditPageBookNotFoundMessage {
            get {
                return ResourceManager.GetString("BookEditPageBookNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch nicht gefunden.
        /// </summary>
        internal static string BookEditPageBookNotFoundTitle {
            get {
                return ResourceManager.GetString("BookEditPageBookNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN existiert bereits.
        /// </summary>
        internal static string BookEditPageISBNDuplicateError {
            get {
                return ResourceManager.GetString("BookEditPageISBNDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges ISBN-Format (ISBN-10 oder ISBN-13 erwartet).
        /// </summary>
        internal static string BookEditPageISBNFormatError {
            get {
                return ResourceManager.GetString("BookEditPageISBNFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string BookEditPageISBNLabel {
            get {
                return ResourceManager.GetString("BookEditPageISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erscheinungsdatum löschen.
        /// </summary>
        internal static string BookEditPagePublishDateClearButtonDescription {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateClearButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✕.
        /// </summary>
        internal static string BookEditPagePublishDateClearButtonText {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erscheinungsdatum.
        /// </summary>
        internal static string BookEditPagePublishDateLabel {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlag darf nicht leer sein.
        /// </summary>
        internal static string BookEditPagePublisherEmptyError {
            get {
                return ResourceManager.GetString("BookEditPagePublisherEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlag.
        /// </summary>
        internal static string BookEditPagePublisherLabel {
            get {
                return ResourceManager.GetString("BookEditPagePublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlag überschreitet maximale Länge von 256 Zeichen.
        /// </summary>
        internal static string BookEditPagePublisherMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPagePublisherMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string BookEditPageSaveButtonText {
            get {
                return ResourceManager.GetString("BookEditPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch bearbeiten.
        /// </summary>
        internal static string BookEditPageTitle {
            get {
                return ResourceManager.GetString("BookEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel darf nicht leer sein.
        /// </summary>
        internal static string BookEditPageTitleEmptyError {
            get {
                return ResourceManager.GetString("BookEditPageTitleEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string BookEditPageTitleLabel {
            get {
                return ResourceManager.GetString("BookEditPageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel überschreitet maximale Länge von 256 Zeichen.
        /// </summary>
        internal static string BookEditPageTitleMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPageTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buch hinzufügen.
        /// </summary>
        internal static string BookListPageAddBookButtonText {
            get {
                return ResourceManager.GetString("BookListPageAddBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Buch hinzufügen.
        /// </summary>
        internal static string BookListPageAddNewBookDescription {
            get {
                return ResourceManager.GetString("BookListPageAddNewBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucheintrag. Tippen zum Bearbeiten. Nach links wischen zum Löschen..
        /// </summary>
        internal static string BookListPageBookEntryDescription {
            get {
                return ResourceManager.GetString("BookListPageBookEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buchliste.
        /// </summary>
        internal static string BookListPageBookListDescription {
            get {
                return ResourceManager.GetString("BookListPageBookListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Bücher. Tippe auf +, um dein erstes Buch hinzuzufügen..
        /// </summary>
        internal static string BookListPageEmptyStateMessage {
            get {
                return ResourceManager.GetString("BookListPageEmptyStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export fehlgeschlagen.
        /// </summary>
        internal static string BookListPageExportErrorMessage {
            get {
                return ResourceManager.GetString("BookListPageExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei gespeichert unter:.
        /// </summary>
        internal static string BookListPageExportFileSavedPrefix {
            get {
                return ResourceManager.GetString("BookListPageExportFileSavedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek exportieren.
        /// </summary>
        internal static string BookListPageExportLibraryButtonText {
            get {
                return ResourceManager.GetString("BookListPageExportLibraryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek als JSON-Datei exportieren.
        /// </summary>
        internal static string BookListPageExportLibraryDescription {
            get {
                return ResourceManager.GetString("BookListPageExportLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothek erfolgreich exportiert.
        /// </summary>
        internal static string BookListPageExportSuccessMessage {
            get {
                return ResourceManager.GetString("BookListPageExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Bücher gefunden.
        /// </summary>
        internal static string BookListPageNoBooksFoundDescription {
            get {
                return ResourceManager.GetString("BookListPageNoBooksFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach Titel, Autor, Verlag oder ISBN suchen.
        /// </summary>
        internal static string BookListPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("BookListPageSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bücher sortieren nach.
        /// </summary>
        internal static string BookListPageSortBooksByDescription {
            get {
                return ResourceManager.GetString("BookListPageSortBooksByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string BookListPageSortByAuthor {
            get {
                return ResourceManager.GetString("BookListPageSortByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erscheinungsdatum.
        /// </summary>
        internal static string BookListPageSortByPublishDate {
            get {
                return ResourceManager.GetString("BookListPageSortByPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlag.
        /// </summary>
        internal static string BookListPageSortByPublisher {
            get {
                return ResourceManager.GetString("BookListPageSortByPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string BookListPageSortByTitle {
            get {
                return ResourceManager.GetString("BookListPageSortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string BookListPageSwipeToDeleteCommand {
            get {
                return ResourceManager.GetString("BookListPageSwipeToDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string BookListPageSwipeToEditCommand {
            get {
                return ResourceManager.GetString("BookListPageSwipeToEditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Fehler.
        /// </summary>
        internal static string BookListPageUnknownErrorMessage {
            get {
                return ResourceManager.GetString("BookListPageUnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen hinzufügen.
        /// </summary>
        internal static string BookmarkEditPageAddTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen nicht gefunden.
        /// </summary>
        internal static string BookmarkEditPageBookmarkNotFoundMessage {
            get {
                return ResourceManager.GetString("BookmarkEditPageBookmarkNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen nicht gefunden.
        /// </summary>
        internal static string BookmarkEditPageBookmarkNotFoundTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageBookmarkNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endseitennummer (optional).
        /// </summary>
        internal static string BookmarkEditPageEndingPageDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endseite (optional).
        /// </summary>
        internal static string BookmarkEditPageEndPageLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endseite muss größer oder gleich der Startseite sein.
        /// </summary>
        internal static string BookmarkEditPageEndPageRangeError {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndPageRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichennote (maximal 1000 Zeichen).
        /// </summary>
        internal static string BookmarkEditPageNoteFieldDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz.
        /// </summary>
        internal static string BookmarkEditPageNoteLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz überschreitet maximale Länge von 1000 Zeichen.
        /// </summary>
        internal static string BookmarkEditPageNoteMaxLengthError {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string BookmarkEditPageSaveButtonText {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichenänderungen speichern.
        /// </summary>
        internal static string BookmarkEditPageSaveChangesDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern fehlgeschlagen.
        /// </summary>
        internal static string BookmarkEditPageSaveFailedMessage {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern fehlgeschlagen.
        /// </summary>
        internal static string BookmarkEditPageSaveFailedTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseitennummer.
        /// </summary>
        internal static string BookmarkEditPageStartingPageDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite muss eine positive Zahl sein.
        /// </summary>
        internal static string BookmarkEditPageStartPageEmptyError {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartPageEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        internal static string BookmarkEditPageStartPageLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesezeichen bearbeiten.
        /// </summary>
        internal static string BookmarkEditPageTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CommonOkButton {
            get {
                return ResourceManager.GetString("CommonOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die lokale Datenbank konnte nicht initialisiert werden..
        /// </summary>
        internal static string LoadingPageErrorMessage {
            get {
                return ResourceManager.GetString("LoadingPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisierung fehlgeschlagen.
        /// </summary>
        internal static string LoadingPageErrorTitle {
            get {
                return ResourceManager.GetString("LoadingPageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        internal static string LoadingPageRetryButtonText {
            get {
                return ResourceManager.GetString("LoadingPageRetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Bibliothek wird vorbereitet....
        /// </summary>
        internal static string LoadingPageStatusText {
            get {
                return ResourceManager.GetString("LoadingPageStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string LoginPageLoginButtonText {
            get {
                return ResourceManager.GetString("LoginPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string LoginPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        internal static string LoginPageRegisterButtonText {
            get {
                return ResourceManager.GetString("LoginPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzername.
        /// </summary>
        internal static string LoginPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("LoginPageUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen.
        /// </summary>
        internal static string RegistrationPageLoginButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        internal static string RegistrationPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        internal static string RegistrationPageRegisterButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierung.
        /// </summary>
        internal static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzername.
        /// </summary>
        internal static string RegistrationPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPageUserNamePlaceholder", resourceCulture);
            }
        }
    }
}
