//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelfly.App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shelfly.App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginPageLoginButtonText {
            get {
                return ResourceManager.GetString("LoginPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageRegisterButtonText {
            get {
                return ResourceManager.GetString("LoginPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("LoginPageUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegistrationPageLoginButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegistrationPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegistrationPageRegisterButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegistrationPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPageUserNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No books yet. Start adding your library!.
        /// </summary>
        internal static string BookListPageEmptyStateMessage {
            get {
                return ResourceManager.GetString("BookListPageEmptyStateMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search by title, author, publisher or ISBN.
        /// </summary>
        internal static string BookListPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("BookListPageSearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by Title.
        /// </summary>
        internal static string BookListPageSortByTitle {
            get {
                return ResourceManager.GetString("BookListPageSortByTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by Author.
        /// </summary>
        internal static string BookListPageSortByAuthor {
            get {
                return ResourceManager.GetString("BookListPageSortByAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by Publisher.
        /// </summary>
        internal static string BookListPageSortByPublisher {
            get {
                return ResourceManager.GetString("BookListPageSortByPublisher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort by Publish Date.
        /// </summary>
        internal static string BookListPageSortByPublishDate {
            get {
                return ResourceManager.GetString("BookListPageSortByPublishDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string BookListPageAddBookButtonText {
            get {
                return ResourceManager.GetString("BookListPageAddBookButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BookListPageSwipeToDeleteCommand {
            get {
                return ResourceManager.GetString("BookListPageSwipeToDeleteCommand", resourceCulture);
            }
        }
    }
}
