//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelfly.App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shelfly.App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string AppShellBooksTitle {
            get {
                return ResourceManager.GetString("AppShellBooksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        internal static string AppShellTrashTitle {
            get {
                return ResourceManager.GetString("AppShellTrashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new bookmark to this book.
        /// </summary>
        internal static string BookDetailPageAddNewBookmarkDescription {
            get {
                return ResourceManager.GetString("BookDetailPageAddNewBookmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string BookDetailPageAuthorLabel {
            get {
                return ResourceManager.GetString("BookDetailPageAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book author.
        /// </summary>
        internal static string BookDetailPageBookAuthorDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookAuthorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark entry. Swipe left to delete. Tap note icon to view note content. Tap edit icon to modify bookmark..
        /// </summary>
        internal static string BookDetailPageBookmarkEntryDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark list.
        /// </summary>
        internal static string BookDetailPageBookmarkListDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}.
        /// </summary>
        internal static string BookDetailPageBookmarkPageLabel {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - {0}.
        /// </summary>
        internal static string BookDetailPageBookmarkRangeLabel {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarkRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks section.
        /// </summary>
        internal static string BookDetailPageBookmarksSectionDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarksSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string BookDetailPageBookmarksTitle {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book publisher.
        /// </summary>
        internal static string BookDetailPageBookPublisherDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookPublisherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title.
        /// </summary>
        internal static string BookDetailPageBookTitleDescription {
            get {
                return ResourceManager.GetString("BookDetailPageBookTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Book.
        /// </summary>
        internal static string BookDetailPageDeleteBookButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageDeleteBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BookDetailPageDeleteBookmarkCommand {
            get {
                return ResourceManager.GetString("BookDetailPageDeleteBookmarkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the book.
        /// </summary>
        internal static string BookDetailPageDeletionFailedMessage {
            get {
                return ResourceManager.GetString("BookDetailPageDeletionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed.
        /// </summary>
        internal static string BookDetailPageDeletionFailedTitle {
            get {
                return ResourceManager.GetString("BookDetailPageDeletionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Book.
        /// </summary>
        internal static string BookDetailPageEditBookButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book details.
        /// </summary>
        internal static string BookDetailPageEditBookDescription {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BookDetailPageEditBookmarkButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookmarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bookmark.
        /// </summary>
        internal static string BookDetailPageEditBookmarkDescription {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book via floating action button.
        /// </summary>
        internal static string BookDetailPageEditFabDescription {
            get {
                return ResourceManager.GetString("BookDetailPageEditFabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Standard Book Number.
        /// </summary>
        internal static string BookDetailPageISBNDescription {
            get {
                return ResourceManager.GetString("BookDetailPageISBNDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string BookDetailPageISBNLabel {
            get {
                return ResourceManager.GetString("BookDetailPageISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string BookDetailPageNoteAlertTitle {
            get {
                return ResourceManager.GetString("BookDetailPageNoteAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show note.
        /// </summary>
        internal static string BookDetailPageNoteIndicatorTooltip {
            get {
                return ResourceManager.GetString("BookDetailPageNoteIndicatorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        internal static string BookDetailPagePublicationDateDescription {
            get {
                return ResourceManager.GetString("BookDetailPagePublicationDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string BookDetailPagePublishDateLabel {
            get {
                return ResourceManager.GetString("BookDetailPagePublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string BookDetailPagePublisherLabel {
            get {
                return ResourceManager.GetString("BookDetailPagePublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft delete book and all bookmarks.
        /// </summary>
        internal static string BookDetailPageSoftDeleteBookDescription {
            get {
                return ResourceManager.GetString("BookDetailPageSoftDeleteBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Details.
        /// </summary>
        internal static string BookDetailPageTitle {
            get {
                return ResourceManager.GetString("BookDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View bookmark note.
        /// </summary>
        internal static string BookDetailPageViewNoteDescription {
            get {
                return ResourceManager.GetString("BookDetailPageViewNoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string BookEditPageAddTitle {
            get {
                return ResourceManager.GetString("BookEditPageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author cannot be empty.
        /// </summary>
        internal static string BookEditPageAuthorEmptyError {
            get {
                return ResourceManager.GetString("BookEditPageAuthorEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string BookEditPageAuthorLabel {
            get {
                return ResourceManager.GetString("BookEditPageAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author exceeds maximum length of 256 characters.
        /// </summary>
        internal static string BookEditPageAuthorMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPageAuthorMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found.
        /// </summary>
        internal static string BookEditPageBookNotFoundMessage {
            get {
                return ResourceManager.GetString("BookEditPageBookNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found.
        /// </summary>
        internal static string BookEditPageBookNotFoundTitle {
            get {
                return ResourceManager.GetString("BookEditPageBookNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Book.
        /// </summary>
        internal static string BookEditPageEditBookTitle {
            get {
                return ResourceManager.GetString("BookEditPageEditBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN already exists.
        /// </summary>
        internal static string BookEditPageISBNDuplicateError {
            get {
                return ResourceManager.GetString("BookEditPageISBNDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISBN format (expected ISBN-10 or ISBN-13).
        /// </summary>
        internal static string BookEditPageISBNFormatError {
            get {
                return ResourceManager.GetString("BookEditPageISBNFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string BookEditPageISBNLabel {
            get {
                return ResourceManager.GetString("BookEditPageISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book.
        /// </summary>
        internal static string BookEditPageNewBookTitle {
            get {
                return ResourceManager.GetString("BookEditPageNewBookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear publish date.
        /// </summary>
        internal static string BookEditPagePublishDateClearButtonDescription {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateClearButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✕.
        /// </summary>
        internal static string BookEditPagePublishDateClearButtonText {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string BookEditPagePublishDateLabel {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher cannot be empty.
        /// </summary>
        internal static string BookEditPagePublisherEmptyError {
            get {
                return ResourceManager.GetString("BookEditPagePublisherEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string BookEditPagePublisherLabel {
            get {
                return ResourceManager.GetString("BookEditPagePublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher exceeds maximum length of 256 characters.
        /// </summary>
        internal static string BookEditPagePublisherMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPagePublisherMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BookEditPageSaveButtonText {
            get {
                return ResourceManager.GetString("BookEditPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save book changes via floating action button.
        /// </summary>
        internal static string BookEditPageSaveFabDescription {
            get {
                return ResourceManager.GetString("BookEditPageSaveFabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        internal static string BookEditPageTitleEmptyError {
            get {
                return ResourceManager.GetString("BookEditPageTitleEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BookEditPageTitleLabel {
            get {
                return ResourceManager.GetString("BookEditPageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title exceeds maximum length of 256 characters.
        /// </summary>
        internal static string BookEditPageTitleMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPageTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string BookListPageAddBookButtonText {
            get {
                return ResourceManager.GetString("BookListPageAddBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new book.
        /// </summary>
        internal static string BookListPageAddNewBookDescription {
            get {
                return ResourceManager.GetString("BookListPageAddNewBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book entry. Tap to edit book. Swipe left to delete..
        /// </summary>
        internal static string BookListPageBookEntryDescription {
            get {
                return ResourceManager.GetString("BookListPageBookEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book list.
        /// </summary>
        internal static string BookListPageBookListDescription {
            get {
                return ResourceManager.GetString("BookListPageBookListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books yet. Tap + to add your first book..
        /// </summary>
        internal static string BookListPageEmptyStateMessage {
            get {
                return ResourceManager.GetString("BookListPageEmptyStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed.
        /// </summary>
        internal static string BookListPageExportErrorMessage {
            get {
                return ResourceManager.GetString("BookListPageExportErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved to:.
        /// </summary>
        internal static string BookListPageExportFileSavedPrefix {
            get {
                return ResourceManager.GetString("BookListPageExportFileSavedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Library.
        /// </summary>
        internal static string BookListPageExportLibraryButtonText {
            get {
                return ResourceManager.GetString("BookListPageExportLibraryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export library to JSON file.
        /// </summary>
        internal static string BookListPageExportLibraryDescription {
            get {
                return ResourceManager.GetString("BookListPageExportLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library exported successfully.
        /// </summary>
        internal static string BookListPageExportSuccessMessage {
            get {
                return ResourceManager.GetString("BookListPageExportSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found.
        /// </summary>
        internal static string BookListPageNoBooksFoundDescription {
            get {
                return ResourceManager.GetString("BookListPageNoBooksFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books matched your search..
        /// </summary>
        internal static string BookListPageSearchEmptyMessage {
            get {
                return ResourceManager.GetString("BookListPageSearchEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by title, author, publisher, or ISBN.
        /// </summary>
        internal static string BookListPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("BookListPageSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort books by.
        /// </summary>
        internal static string BookListPageSortBooksByDescription {
            get {
                return ResourceManager.GetString("BookListPageSortBooksByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string BookListPageSortByAuthor {
            get {
                return ResourceManager.GetString("BookListPageSortByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string BookListPageSortByPublishDate {
            get {
                return ResourceManager.GetString("BookListPageSortByPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string BookListPageSortByPublisher {
            get {
                return ResourceManager.GetString("BookListPageSortByPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BookListPageSortByTitle {
            get {
                return ResourceManager.GetString("BookListPageSortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BookListPageSwipeToDeleteCommand {
            get {
                return ResourceManager.GetString("BookListPageSwipeToDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BookListPageSwipeToEditCommand {
            get {
                return ResourceManager.GetString("BookListPageSwipeToEditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Library.
        /// </summary>
        internal static string BookListPageTitle {
            get {
                return ResourceManager.GetString("BookListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string BookListPageUnknownErrorMessage {
            get {
                return ResourceManager.GetString("BookListPageUnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        internal static string BookmarkEditPageAddTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark not found.
        /// </summary>
        internal static string BookmarkEditPageBookmarkNotFoundMessage {
            get {
                return ResourceManager.GetString("BookmarkEditPageBookmarkNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark not found.
        /// </summary>
        internal static string BookmarkEditPageBookmarkNotFoundTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageBookmarkNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bookmark.
        /// </summary>
        internal static string BookmarkEditPageEditBookmarkTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageEditBookmarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending page number (optional).
        /// </summary>
        internal static string BookmarkEditPageEndingPageDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Page (optional).
        /// </summary>
        internal static string BookmarkEditPageEndPageLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End page must be greater than or equal to start page.
        /// </summary>
        internal static string BookmarkEditPageEndPageRangeError {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndPageRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bookmark.
        /// </summary>
        internal static string BookmarkEditPageNewBookmarkTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageNewBookmarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark note (maximum 1000 characters).
        /// </summary>
        internal static string BookmarkEditPageNoteFieldDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string BookmarkEditPageNoteLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note exceeds maximum length of 1000 characters.
        /// </summary>
        internal static string BookmarkEditPageNoteMaxLengthError {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BookmarkEditPageSaveButtonText {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bookmark changes.
        /// </summary>
        internal static string BookmarkEditPageSaveChangesDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save bookmark via floating action button.
        /// </summary>
        internal static string BookmarkEditPageSaveFabDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveFabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string BookmarkEditPageSaveFailedMessage {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        internal static string BookmarkEditPageSaveFailedTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting page number.
        /// </summary>
        internal static string BookmarkEditPageStartingPageDescription {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartingPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page must be a positive number.
        /// </summary>
        internal static string BookmarkEditPageStartPageEmptyError {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartPageEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        internal static string BookmarkEditPageStartPageLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CommonOkButton {
            get {
                return ResourceManager.GetString("CommonOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local database could not be initialized..
        /// </summary>
        internal static string LoadingPageErrorMessage {
            get {
                return ResourceManager.GetString("LoadingPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed.
        /// </summary>
        internal static string LoadingPageErrorTitle {
            get {
                return ResourceManager.GetString("LoadingPageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string LoadingPageRetryButtonText {
            get {
                return ResourceManager.GetString("LoadingPageRetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing your library....
        /// </summary>
        internal static string LoadingPageStatusText {
            get {
                return ResourceManager.GetString("LoadingPageStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginPageLoginButtonText {
            get {
                return ResourceManager.GetString("LoginPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageRegisterButtonText {
            get {
                return ResourceManager.GetString("LoginPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("LoginPageUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegistrationPageLoginButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegistrationPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegistrationPageRegisterButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegistrationPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPageUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string SortDirectionAscending {
            get {
                return ResourceManager.GetString("SortDirectionAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string SortDirectionDescending {
            get {
                return ResourceManager.GetString("SortDirectionDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Details.
        /// </summary>
        internal static string TrashBookDetailPageTitle {
            get {
                return ResourceManager.GetString("TrashBookDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash entry. Tap to view details. Swipe left to restore, swipe right to delete..
        /// </summary>
        internal static string TrashListPageBookEntryDescription {
            get {
                return ResourceManager.GetString("TrashListPageBookEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string TrashListPageDeleteAllButtonText {
            get {
                return ResourceManager.GetString("TrashListPageDeleteAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all items permanently.
        /// </summary>
        internal static string TrashListPageDeleteAllDescription {
            get {
                return ResourceManager.GetString("TrashListPageDeleteAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete all items from trash..
        /// </summary>
        internal static string TrashListPageDeleteAllDialogMessage {
            get {
                return ResourceManager.GetString("TrashListPageDeleteAllDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Items?.
        /// </summary>
        internal static string TrashListPageDeleteAllDialogTitle {
            get {
                return ResourceManager.GetString("TrashListPageDeleteAllDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        internal static string TrashListPageDeleteSelectedButtonText {
            get {
                return ResourceManager.GetString("TrashListPageDeleteSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items permanently.
        /// </summary>
        internal static string TrashListPageDeleteSelectedDescription {
            get {
                return ResourceManager.GetString("TrashListPageDeleteSelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TrashListPageDoneButtonText {
            get {
                return ResourceManager.GetString("TrashListPageDoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit selection mode.
        /// </summary>
        internal static string TrashListPageDoneSelectionDescription {
            get {
                return ResourceManager.GetString("TrashListPageDoneSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items in trash..
        /// </summary>
        internal static string TrashListPageEmptyStateMessage {
            get {
                return ResourceManager.GetString("TrashListPageEmptyStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore All.
        /// </summary>
        internal static string TrashListPageRestoreAllButtonText {
            get {
                return ResourceManager.GetString("TrashListPageRestoreAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore all items from trash.
        /// </summary>
        internal static string TrashListPageRestoreAllDescription {
            get {
                return ResourceManager.GetString("TrashListPageRestoreAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will restore all items from trash back to your library..
        /// </summary>
        internal static string TrashListPageRestoreAllDialogMessage {
            get {
                return ResourceManager.GetString("TrashListPageRestoreAllDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore All Items?.
        /// </summary>
        internal static string TrashListPageRestoreAllDialogTitle {
            get {
                return ResourceManager.GetString("TrashListPageRestoreAllDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Selected.
        /// </summary>
        internal static string TrashListPageRestoreSelectedButtonText {
            get {
                return ResourceManager.GetString("TrashListPageRestoreSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore selected items to library.
        /// </summary>
        internal static string TrashListPageRestoreSelectedDescription {
            get {
                return ResourceManager.GetString("TrashListPageRestoreSelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items matched your search..
        /// </summary>
        internal static string TrashListPageSearchEmptyMessage {
            get {
                return ResourceManager.GetString("TrashListPageSearchEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by title, author, publisher, or ISBN.
        /// </summary>
        internal static string TrashListPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("TrashListPageSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TrashListPageSwipeToDeleteCommand {
            get {
                return ResourceManager.GetString("TrashListPageSwipeToDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string TrashListPageSwipeToRestoreCommand {
            get {
                return ResourceManager.GetString("TrashListPageSwipeToRestoreCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        internal static string TrashListPageTitle {
            get {
                return ResourceManager.GetString("TrashListPageTitle", resourceCulture);
            }
        }
    }
}
