//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shelfly.App.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shelfly.App.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        internal static string BookDetailPageAddBookmarkButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageAddBookmarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string BookDetailPageAuthorLabel {
            get {
                return ResourceManager.GetString("BookDetailPageAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string BookDetailPageBookmarksTitle {
            get {
                return ResourceManager.GetString("BookDetailPageBookmarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Book.
        /// </summary>
        internal static string BookDetailPageDeleteBookButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageDeleteBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BookDetailPageDeleteBookmarkCommand {
            get {
                return ResourceManager.GetString("BookDetailPageDeleteBookmarkCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BookDetailPageEditBookmarkButtonText {
            get {
                return ResourceManager.GetString("BookDetailPageEditBookmarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string BookDetailPageISBNLabel {
            get {
                return ResourceManager.GetString("BookDetailPageISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show note.
        /// </summary>
        internal static string BookDetailPageNoteIndicatorTooltip {
            get {
                return ResourceManager.GetString("BookDetailPageNoteIndicatorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string BookDetailPagePublishDateLabel {
            get {
                return ResourceManager.GetString("BookDetailPagePublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string BookDetailPagePublisherLabel {
            get {
                return ResourceManager.GetString("BookDetailPagePublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Details.
        /// </summary>
        internal static string BookDetailPageTitle {
            get {
                return ResourceManager.GetString("BookDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string BookEditPageAddTitle {
            get {
                return ResourceManager.GetString("BookEditPageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author cannot be empty.
        /// </summary>
        internal static string BookEditPageAuthorEmptyError {
            get {
                return ResourceManager.GetString("BookEditPageAuthorEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string BookEditPageAuthorLabel {
            get {
                return ResourceManager.GetString("BookEditPageAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author exceeds maximum length of 256 characters.
        /// </summary>
        internal static string BookEditPageAuthorMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPageAuthorMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN already exists.
        /// </summary>
        internal static string BookEditPageISBNDuplicateError {
            get {
                return ResourceManager.GetString("BookEditPageISBNDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ISBN format (expected ISBN-10 or ISBN-13).
        /// </summary>
        internal static string BookEditPageISBNFormatError {
            get {
                return ResourceManager.GetString("BookEditPageISBNFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string BookEditPageISBNLabel {
            get {
                return ResourceManager.GetString("BookEditPageISBNLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string BookEditPagePublishDateLabel {
            get {
                return ResourceManager.GetString("BookEditPagePublishDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher cannot be empty.
        /// </summary>
        internal static string BookEditPagePublisherEmptyError {
            get {
                return ResourceManager.GetString("BookEditPagePublisherEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string BookEditPagePublisherLabel {
            get {
                return ResourceManager.GetString("BookEditPagePublisherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher exceeds maximum length of 256 characters.
        /// </summary>
        internal static string BookEditPagePublisherMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPagePublisherMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BookEditPageSaveButtonText {
            get {
                return ResourceManager.GetString("BookEditPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Book.
        /// </summary>
        internal static string BookEditPageTitle {
            get {
                return ResourceManager.GetString("BookEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        internal static string BookEditPageTitleEmptyError {
            get {
                return ResourceManager.GetString("BookEditPageTitleEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BookEditPageTitleLabel {
            get {
                return ResourceManager.GetString("BookEditPageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title exceeds maximum length of 256 characters.
        /// </summary>
        internal static string BookEditPageTitleMaxLengthError {
            get {
                return ResourceManager.GetString("BookEditPageTitleMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string BookListPageAddBookButtonText {
            get {
                return ResourceManager.GetString("BookListPageAddBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books yet. Tap + to add your first book..
        /// </summary>
        internal static string BookListPageEmptyStateMessage {
            get {
                return ResourceManager.GetString("BookListPageEmptyStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by title, author, publisher, or ISBN.
        /// </summary>
        internal static string BookListPageSearchPlaceholder {
            get {
                return ResourceManager.GetString("BookListPageSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string BookListPageSortByAuthor {
            get {
                return ResourceManager.GetString("BookListPageSortByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        internal static string BookListPageSortByPublishDate {
            get {
                return ResourceManager.GetString("BookListPageSortByPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string BookListPageSortByPublisher {
            get {
                return ResourceManager.GetString("BookListPageSortByPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string BookListPageSortByTitle {
            get {
                return ResourceManager.GetString("BookListPageSortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BookListPageSwipeToDeleteCommand {
            get {
                return ResourceManager.GetString("BookListPageSwipeToDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        internal static string BookmarkEditPageAddTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Page (optional).
        /// </summary>
        internal static string BookmarkEditPageEndPageLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End page must be greater than or equal to start page.
        /// </summary>
        internal static string BookmarkEditPageEndPageRangeError {
            get {
                return ResourceManager.GetString("BookmarkEditPageEndPageRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string BookmarkEditPageNoteLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note exceeds maximum length of 1000 characters.
        /// </summary>
        internal static string BookmarkEditPageNoteMaxLengthError {
            get {
                return ResourceManager.GetString("BookmarkEditPageNoteMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BookmarkEditPageSaveButtonText {
            get {
                return ResourceManager.GetString("BookmarkEditPageSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page must be a positive number.
        /// </summary>
        internal static string BookmarkEditPageStartPageEmptyError {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartPageEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        internal static string BookmarkEditPageStartPageLabel {
            get {
                return ResourceManager.GetString("BookmarkEditPageStartPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bookmark.
        /// </summary>
        internal static string BookmarkEditPageTitle {
            get {
                return ResourceManager.GetString("BookmarkEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginPageLoginButtonText {
            get {
                return ResourceManager.GetString("LoginPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageRegisterButtonText {
            get {
                return ResourceManager.GetString("LoginPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("LoginPageUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string RegistrationPageLoginButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string RegistrationPagePasswordPlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPagePasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegistrationPageRegisterButtonText {
            get {
                return ResourceManager.GetString("RegistrationPageRegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string RegistrationPageTitle {
            get {
                return ResourceManager.GetString("RegistrationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string RegistrationPageUserNamePlaceholder {
            get {
                return ResourceManager.GetString("RegistrationPageUserNamePlaceholder", resourceCulture);
            }
        }
    }
}
