// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Shelfly.Api.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Bookmark : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Parent book reference; cascade delete on parent hard deletion</summary>
        public Guid? BookId { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>Ending page number (for multi-page bookmarks); must be &gt;= startPage</summary>
        public int? EndPage { get; set; }
        /// <summary>Entity identifier (UUID v7, time-ordered)</summary>
        public Guid? Id { get; set; }
        /// <summary>Last modification timestamp; used for last-write-wins synchronization</summary>
        public DateTimeOffset? LastModifiedAt { get; private set; }
        /// <summary>User annotation text</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>Starting page number</summary>
        public int? StartPage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Shelfly.Api.Client.Models.Bookmark"/> and sets the default values.
        /// </summary>
        public Bookmark()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Shelfly.Api.Client.Models.Bookmark"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Shelfly.Api.Client.Models.Bookmark CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Shelfly.Api.Client.Models.Bookmark();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bookId", n => { BookId = n.GetGuidValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "endPage", n => { EndPage = n.GetIntValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "lastModifiedAt", n => { LastModifiedAt = n.GetDateTimeOffsetValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "startPage", n => { StartPage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("bookId", BookId);
            writer.WriteIntValue("endPage", EndPage);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("note", Note);
            writer.WriteIntValue("startPage", StartPage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
