// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Shelfly.Api.Client.Models;
using Shelfly.Api.Client.V1.Bookmarks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Shelfly.Api.Client.V1.Bookmarks
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\bookmarks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BookmarksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Shelfly.Api.Client.v1.bookmarks.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Shelfly.Api.Client.V1.Bookmarks.Item.BookmarksItemRequestBuilder"/></returns>
        public global::Shelfly.Api.Client.V1.Bookmarks.Item.BookmarksItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Shelfly.Api.Client.V1.Bookmarks.Item.BookmarksItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Shelfly.Api.Client.v1.bookmarks.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Shelfly.Api.Client.V1.Bookmarks.Item.BookmarksItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Shelfly.Api.Client.V1.Bookmarks.Item.BookmarksItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::Shelfly.Api.Client.V1.Bookmarks.Item.BookmarksItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookmarksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/bookmarks{?bookId*,page*,pageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BookmarksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/bookmarks{?bookId*,page*,pageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// List bookmarks
        /// </summary>
        /// <returns>A <see cref="global::Shelfly.Api.Client.V1.Bookmarks.BookmarksGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Shelfly.Api.Client.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksGetResponse?> GetAsBookmarksGetResponseAsync(Action<RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksGetResponse> GetAsBookmarksGetResponseAsync(Action<RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Shelfly.Api.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksGetResponse>(requestInfo, global::Shelfly.Api.Client.V1.Bookmarks.BookmarksGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List bookmarks
        /// </summary>
        /// <returns>A <see cref="global::Shelfly.Api.Client.V1.Bookmarks.BookmarksResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Shelfly.Api.Client.Models.ProblemDetails">When receiving a 401 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsBookmarksGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksResponse?> GetAsync(Action<RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksResponse> GetAsync(Action<RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Shelfly.Api.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksResponse>(requestInfo, global::Shelfly.Api.Client.V1.Bookmarks.BookmarksResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new bookmark
        /// </summary>
        /// <returns>A <see cref="global::Shelfly.Api.Client.Models.Bookmark"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Shelfly.Api.Client.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::Shelfly.Api.Client.Models.ProblemDetails">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Shelfly.Api.Client.Models.Bookmark?> PostAsync(global::Shelfly.Api.Client.Models.BookmarkCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Shelfly.Api.Client.Models.Bookmark> PostAsync(global::Shelfly.Api.Client.Models.BookmarkCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Shelfly.Api.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "401", global::Shelfly.Api.Client.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Shelfly.Api.Client.Models.Bookmark>(requestInfo, global::Shelfly.Api.Client.Models.Bookmark.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List bookmarks
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new bookmark
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Shelfly.Api.Client.Models.BookmarkCreate body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Shelfly.Api.Client.Models.BookmarkCreate body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List bookmarks
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookmarksRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by parent book ID</summary>
            [QueryParameter("bookId")]
            public Guid? BookId { get; set; }
            /// <summary>Page number (1-indexed)</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Items per page</summary>
            [QueryParameter("pageSize")]
            public int? PageSize { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookmarksRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Shelfly.Api.Client.V1.Bookmarks.BookmarksRequestBuilder.BookmarksRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BookmarksRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
