// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelfly.App.Data;

#nullable disable

namespace Shelfly.App.Migrations.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260917160212_AddServerSyncEntities")]
    partial class AddServerSyncEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("ISBN", "Id");

                    b.HasIndex("Title", "Author", "Publisher");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookProfileSyncRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileUsername");

                    b.HasIndex("BookId", "ProfileUsername")
                        .IsUnique();

                    b.ToTable("BookProfileSyncRecords");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookServerMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerAssignedId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("BookId", "ServerId")
                        .IsUnique();

                    b.HasIndex("ServerAssignedId", "ServerId");

                    b.ToTable("BookServerMappings");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookmarkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndPage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartPage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BookId", "StartPage");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.SavedServerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ServerId");

                    b.ToTable("SavedServerEntries");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.ServerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.SyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveServerEntryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncResult")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActiveServerEntryId");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookProfileSyncRecord", b =>
                {
                    b.HasOne("Shelfly.App.Data.Entities.BookEntity", "Book")
                        .WithMany("ProfileSyncRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookServerMapping", b =>
                {
                    b.HasOne("Shelfly.App.Data.Entities.BookEntity", "Book")
                        .WithMany("ServerMappings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shelfly.App.Data.Entities.ServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("Shelfly.App.Data.Entities.BookEntity", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.SavedServerEntry", b =>
                {
                    b.HasOne("Shelfly.App.Data.Entities.ServerEntity", "Server")
                        .WithMany("SavedEntries")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.SyncState", b =>
                {
                    b.HasOne("Shelfly.App.Data.Entities.SavedServerEntry", "ActiveServerEntry")
                        .WithMany()
                        .HasForeignKey("ActiveServerEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveServerEntry");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.BookEntity", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("ProfileSyncRecords");

                    b.Navigation("ServerMappings");
                });

            modelBuilder.Entity("Shelfly.App.Data.Entities.ServerEntity", b =>
                {
                    b.Navigation("SavedEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
