FROM postgres:18.4

COPY 01-create-shelfly-db.sql /docker-entrypoint-initdb.d/
COPY 01b-create-shelfly-admin.sql /docker-entrypoint-initdb.d/
COPY 02-create-shelfly-user.sql /docker-entrypoint-initdb.d/

ENTRYPOINT [ "sh", "-c", "export PGPASSWORD=$(cat /run/secrets/postgres_password) && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /docker-entrypoint-initdb.d/01-create-shelfly-db.sql && psql -U ${POSTGRES_USER} -d ${SHELFLY_DB} -f /docker-entrypoint-initdb.d/01b-create-shelfly-admin.sql && psql -U ${POSTGRES_USER} -d ${SHELFLY_DB} -f /docker-entrypoint-initdb.d/02-create-shelfly-user.sql" ]
